FROM openjdk:11-jdk-slim
MAINTAINER My Company (it@mycompany.com)

ARG JAR_FILE
ARG PAAS_TOKEN
ENV JAVA_OPTS=""
ENV TOKEN=$PAAS_TOKEN

RUN apt-get update; apt-get install -y curl; apt-get install -y openssl
COPY $JAR_FILE /app/app.jar

RUN curl -k -H "Authorization: Api-Token $TOKEN" "https://ybc21478.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?arch=x86&flavor=default" --output Dynatrace-OneAgent-Linux-1.247.240.sh
RUN curl -k https://ca.dynatrace.com/dt-root.cert.pem --output dt-root.cert.pem; ( echo 'Content-Type: multipart/signed; protocol="application/x-pkcs7-signature"; micalg="sha-256"; boundary="--SIGNED-INSTALLER"'; echo ; echo ; echo '----SIGNED-INSTALLER' ; cat Dynatrace-OneAgent-Linux-1.247.240.sh ) | openssl cms -verify -CAfile dt-root.cert.pem > /dev/null
RUN /bin/sh Dynatrace-OneAgent-Linux-1.247.240.sh --set-infra-only=false --set-app-log-content-access=true

ENTRYPOINT exec java $JAVA_OPTS -jar /app/app.jar